In [66]:
# Colab Sector 
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [67]:
!ls

diabetes_null.csv  Insurance.xlsx  unprocessed_data.csv


In [68]:
import os 
os.chdir('drive/My Drive/Fusion')

FileNotFoundError: ignored

In [ ]:
!ls

# Data Preprocessing Tutorial

In [71]:
# import our modules 
import numpy as np
import pandas as pd

### First let's import our dataset and take a look to it.

In [84]:
df = pd.read_csv('unprocessed_data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [85]:
y= df['Purchased']
X=df.drop(['Purchased'],1)
X

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  


Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

## Start with First Column its Categorical so Lets Turn it into  Dummies 

In [86]:
X=pd.get_dummies(X)
X

Age   Salary  Country_France  Country_Germany  Country_Spain
0  44.0  72000.0               1                0              0
1  27.0  48000.0               0                0              1
2  30.0  54000.0               0                1              0
3  38.0  61000.0               0                0              1
4  40.0      NaN               0                1              0
5  35.0  58000.0               1                0              0
6   NaN  52000.0               0                0              1
7  48.0  79000.0               1                0              0
8  50.0  83000.0               0                1              0
9  37.0  67000.0               1                0              0

## Handling the missing data
 we have two options : 
 1. remove the row 
 It can be done easily through excel or pandas or numpy by slicing
 2. replace it by the mean 
 It also can be done with many ways but lets use Imputer

In [87]:
from sklearn.impute import SimpleImputer 
# Call the Simple Imputer Class and pass the Necessary Arguments
imputer = SimpleImputer(missing_values= np.nan, strategy='mean') #np.nan means all the Empty cells in the array
# Fit The imputer on the Desired Columns then Transform it 
X = imputer.fit_transform(X.values)
X

array([[4.40000000e+01, 7.20000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [2.70000000e+01, 4.80000000e+04, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00],
       [3.00000000e+01, 5.40000000e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [3.80000000e+01, 6.10000000e+04, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00],
       [4.00000000e+01, 6.37777778e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [3.50000000e+01, 5.80000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [3.87777778e+01, 5.20000000e+04, 0.00000000e+00, 0.00000000e+00,
        1.00000000e+00],
       [4.80000000e+01, 7.90000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [5.00000000e+01, 8.30000000e+04, 0.00000000e+00, 1.00000000e+00,
        0.00000000e+00],
       [3.70000000e+01, 6.70000000e+04, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00]])

In [88]:
# UGLY?
X=X.astype(int)
X

array([[   44, 72000,     1,     0,     0],
       [   27, 48000,     0,     0,     1],
       [   30, 54000,     0,     1,     0],
       [   38, 61000,     0,     0,     1],
       [   40, 63777,     0,     1,     0],
       [   35, 58000,     1,     0,     0],
       [   38, 52000,     0,     0,     1],
       [   48, 79000,     1,     0,     0],
       [   50, 83000,     0,     1,     0],
       [   37, 67000,     1,     0,     0]])

## Handling Binary Categories

In [89]:
# import the needed librarys
#to Deal with Categorical Label
from sklearn.preprocessing import LabelEncoder
print(y)
encoder = LabelEncoder()
label_vector = encoder.fit_transform(y)
label_vector

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object


array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## Now we need to split our data to train and test data ..

In [90]:
# import the modules 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(len(X_train))
print(len(X_test))
print(len(X))


8
2
10


# Okay, what about that diversity in the values in the salary column ?
 well, this might cause us a problem with a model that runs using the euclidean distance, as the variable with large values might dominate the other variable, thus make unclear predictions, so it's better to scale/standardize our features value, so that they have the same scale
### Also because this help the algorithm to converge much much faster 

In [91]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
# take a look how the values was before and after the scalling 
print('before scalling, max is %d and min is %d'%(np.max(X_train), np.min(X_train)))
# Learn the paramters from X_train and  Transfrom  X_Train
X_train = scaler.fit_transform(X_train)
# Then transform X_test 
X_test = scaler.transform(X_test)
print('after scalling, max is %d and min is %d'%(np.max(X_train), np.min(X_train)))

before scalling, max is 79000 and min is 0
after scalling, max is 2 and min is -1


# Now it's Your Turn  
Call this  [Data](https://raw.githubusercontent.com/SagarGaniga/Data-Preprocessing/master/diabetes_null.csv)

**First** Load The Data over here 

In [92]:
!ls

diabetes_null.csv  Insurance.xlsx  unprocessed_data.csv


In [94]:
df = pd.read_csv('diabetes_null.csv')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0      NaN  33.6   
1              1     85.0           66.0           29.0      NaN  26.6   
2              8    183.0           64.0            NaN      NaN  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0            4.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10     11.0           76.0           48.0     18.0  32.9   
764            2    122.0            7.0           27.0      NaN  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0            6.0            NaN      NaN   3.1   
767            1     93.0            7.0           31.0      NaN   3.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627    5        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245    3        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [95]:
y= df['Outcome']
X=df.drop(['Outcome'],1)
X

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6    148.0           72.0           35.0      NaN  33.6   
1              1     85.0           66.0           29.0      NaN  26.6   
2              8    183.0           64.0            NaN      NaN  23.3   
3              1     89.0           66.0           23.0     94.0  28.1   
4              0    137.0            4.0           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10     11.0           76.0           48.0     18.0  32.9   
764            2    122.0            7.0           27.0      NaN  36.8   
765            5    121.0           72.0           23.0    112.0  26.2   
766            1    126.0            6.0            NaN      NaN   3.1   
767            1     93.0            7.0           31.0      NaN   3.4   

     DiabetesPedigreeFunction  Age  
0                       0.627    5  
1                       0.351   31  
2                       0.672   32  
3                       0.167   21  
4                       2.288   33  
..                        ...  ...  
763                     0.171   63  
764                     0.340   27  
765                     0.245    3  
766                     0.349   47  
767                     0.315   23  

[768 rows x 8 columns]

**Second** Try to do all the required Preprocessing that it might needs.


In [96]:
from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values= np.nan, strategy='mean') #np.nan means all the Empty cells in the array
X = imputer.fit_transform(X.values)
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,   5.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,   3.   ],
       [  1.   , 126.   ,   6.   , ...,   3.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,   7.   , ...,   3.4  ,   0.315,  23.   ]])

In [107]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(len(X_train))
print(len(X_test))
print(len(X))

614
154
768


In [98]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# print('before scalling, max is %d and min is %d'%(np.max(X_train), np.min(X_train)))
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)
# print('after scalling, max is %d and min is %d'%(np.max(X_train), np.min(X_train)))


before scalling, max is 846 and min is 0
after scalling, max is 8 and min is -2


In [108]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
print('before scalling, max is %d and min is %d'%(np.max(X_train), np.min(X_train)))
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
print('after scalling, max is %d and min is %d'%(np.max(X_train), np.min(X_train)))

before scalling, max is 846 and min is 0
after scalling, max is 1 and min is 0
